services:
  postgres:
    image: ankane/pgvector:v0.5.0
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vector_store
      - PGPASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    healthcheck:
      test: "pg_isready -U postgres -d vector_store"
      interval: 2s
      timeout: 20s
      retries: 10

  neo4j:
    image: neo4j:5.9.0
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/postgres
      - NEO4J_dbms_memory_pagecache_size=512M
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
    ports:
      - '7474:7474'
      - '7687:7687'
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p postgres 'RETURN 1'"]
      interval: 10s
      retries: 10